// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zE_103G9KmMhLJKj-2fEsX1nwKDIrZc',
    appId: '1:294929170589:web:1f20edd0489f60c477d474',
    messagingSenderId: '294929170589',
    projectId: 'super-mockers',
    authDomain: 'super-mockers.firebaseapp.com',
    databaseURL: 'https://super-mockers-default-rtdb.firebaseio.com',
    storageBucket: 'super-mockers.appspot.com',
    measurementId: 'G-7VYWHLFJN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZ77nC9gH_oFrvc8YUndUv-4Nb4sZCAc',
    appId: '1:294929170589:android:56452663ea953b3a77d474',
    messagingSenderId: '294929170589',
    projectId: 'super-mockers',
    databaseURL: 'https://super-mockers-default-rtdb.firebaseio.com',
    storageBucket: 'super-mockers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXWg_25sESuH_-4BeN1_0brU49CObifZU',
    appId: '1:294929170589:ios:0903410bbe4c54ee77d474',
    messagingSenderId: '294929170589',
    projectId: 'super-mockers',
    databaseURL: 'https://super-mockers-default-rtdb.firebaseio.com',
    storageBucket: 'super-mockers.appspot.com',
    androidClientId: '294929170589-875rvpiihuh897spijhbq6heaee7ndqi.apps.googleusercontent.com',
    iosClientId: '294929170589-5cdmb0t3qut7gj7hdpjlaphr7b4lq0id.apps.googleusercontent.com',
    iosBundleId: 'com.augmentedfuture.g',
  );
}
